/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 099f554905ad8758107b57cb6837621d)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker/index')
  }
  interface Env {
    NONCE_STORE: KVNamespace
    BETTER_AUTH_SIWE_DOMAIN: string
    BETTER_AUTH_SECRET: string
    DB: D1Database
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<Cloudflare.Env, 'BETTER_AUTH_SIWE_DOMAIN' | 'BETTER_AUTH_SECRET'>
    > {}
}
