services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    entrypoint: ["anvil"]
    command: --odyssey --host 0.0.0.0 --port 8545
    labels:
      - dev.orbstack.domains=anvil.local
    ports:
      - "8545:8545"
    healthcheck:
      test: ["CMD", "cast", "block-number", "--rpc-url", "http://localhost:8545"]
      interval: 2s
      retries: 5

  config:
    depends_on:
      anvil:
        condition: service_healthy
    build:
      context: ./docker/config
      dockerfile: Dockerfile
    user: root
    entrypoint: /bin/sh
    volumes:
      - ./contracts/account:/app/account
      - ./contracts/demo:/app/demo
      - ./docker/config:/app/
      - relay:/app/shared
    command: -c "bash ./run.sh"

  relay:
    image: ghcr.io/ithacaxyz/relay:3fc0de2
    platform: linux/x86_64
    labels:
      - dev.orbstack.domains=relay.local
    ports:
      - "9119:9119"
    volumes:
      - relay:/app
    depends_on:
      config:
        condition: service_completed_successfully
    environment:
      RUST_LOG: debug
      RELAY_MNEMONIC: "test test test test test test test test test test test junk"
    command: --config-only --registry /app/registry.yaml
      
volumes:
  relay: