packages:
  - 'app'
  - 'examples/*'
  - 'playground'
  - 'src'

catalog:
  "@tanstack/react-query": "^5.59.20"
  "@types/react": "^18.3.3"
  "@types/react-dom": "^18.3.0"
  globals: "^15.14.0"
  react: "^18.3.1"
  react-dom: "^18.3.1"
  typescript: "^5.7.3"
  viem: "^2.22.3"
  wagmi: "^2.14.5"
  "@wagmi/core": "^2.16.3"
