auditConfig:
  ignoreGhsas:
    - GHSA-ffrw-9mx8-89p8
catalog:
  "@ariakit/react": "^0.4.18"
  "@ariakit/tailwind": "^0.1.8"
  "@iconify/json": "^2.2.386"
  "@pandacss/dev": "^0.54.0"
  "@sentry/react": "^10.17.0"
  "@sentry/vite-plugin": "^4.3.0"
  "@svgr/core": "^8.1.0"
  "@svgr/plugin-jsx": "^8.1.0"
  "@tailwindcss/vite": "^4.1.13"
  "@tanstack/query-async-storage-persister": "^5.90.2"
  "@tanstack/query-sync-storage-persister": "^5.90.1"
  "@tanstack/react-query": "^5.90.2"
  "@tanstack/react-query-devtools": "^5.90.2"
  "@tanstack/react-query-persist-client": "5.90.2"
  "@tanstack/react-router": "^1.132.31"
  "@tanstack/react-router-devtools": "^1.132.31"
  "@tanstack/router-plugin": "^1.132.31"
  "@types/node": "^24.5.2"
  "@types/react": "^19.1.14"
  "@types/react-dom": "^19.1.9"
  "@vitejs/plugin-react": "^5.0.3"
  "@wagmi/core": "^2.21.2"
  cva: "npm:class-variance-authority@^0.7.1"
  globals: "^16.4.0"
  ox: "^0.9.6"
  postcss: "^8.5.6"
  prool: "^0.0.23"
  react: "^19.1.1"
  react-dom: "^19.1.1"
  sonner: "^2.0.7"
  tailwindcss: "^4.1.13"
  tw-animate-css: "^1.3.8"
  typescript: "~5.9.2"
  unplugin-icons: "^22.3.0"
  viem: "^2.37.8"
  vite: "^7.1.7"
  vite-plugin-mkcert: "^1.17.8"
  vitest: "4.0.0-beta.10"
  wagmi: "^2.17.5"
  zod: "4.1.11"
  zustand: "^5.0.3"
minimumReleaseAge: 2880 # 48 hours
minimumReleaseAgeExclude:
  - "@wagmi/connectors"
  - "@wagmi/core"
  - wagmi
  - wshy
packages:
  - "."
  - "apps/*"
  - "docker/*"
  - "examples/*"