packages:
  - 'app'
  - 'demo'
  - 'docs'
  - 'examples/*'
  - 'extension'
  - 'playground'
  - 'src'

catalog:
  "@tanstack/react-query": "^5.66.9"
  "@types/react": "^19"
  "@types/react-dom": "^19"
  "@wagmi/core": "^2.16.3"
  globals: "^16.0.0"
  ox: "^0.6.10"
  react: "^19"
  react-dom: "^19"
  tailwindcss: "^4.0.12"
  "@tailwindcss/vite": "^4.0.9"
  typescript: "^5.8.2"
  viem: "^2.23.8"
  wagmi: "^2.14.11"
