packages:
  - 'apps/*'
  - 'demo'
  - 'examples/*'
  - 'extension'
  - 'src'

catalog:
  "@iconify/json": "^2.2.318"
  "@sentry/react": "^9"
  "@sentry/vite-plugin": "^3"
  "@svgr/core": "^8.1.0"
  "@svgr/plugin-jsx": "^8.1.0"
  "@tanstack/query-sync-storage-persister": "^5.68.0"
  "@tanstack/react-query": "^5.68.0"
  "@tanstack/react-query-persist-client": "^5.68.0"
  "@tanstack/react-router": "^1.114.25"
  "@tanstack/router-plugin": "^1.114.17"
  "@tanstack/react-query-devtools": "^5.68.0"
  "@tanstack/react-router-devtools": "^1.114.25"
  "@types/react": "^19"
  "@types/react-dom": "^19"
  "@wagmi/core": "^2.16.7"
  cva: "npm:class-variance-authority@^0.7.1"
  globals: "^16.0.0"
  ox: "^0.6.12"
  react: "^19"
  react-dom: "^19"
  tailwindcss: "^4.0.15"
  "@tailwindcss/vite": "^4.0.15"
  typescript: "^5.8.2"
  unplugin-icons: "^22.1.0"
  viem: "2.26.0-canary-20250406061806"
  vite: "^6.0.7"
  vite-plugin-mkcert: "^1.17.8"
  wagmi: "^2.14.15"
  zustand: "^5.0.3"
  "@vitejs/plugin-react": "^4.3.4"
