packages:
  - "apps/*"
  - "docker/*"
  - "examples/*"
  - "src"
  - "!**/_/**"

catalog:
  "@ariakit/react": "^0.4.18"
  "@ariakit/tailwind": "^0.1.7"
  "@iconify/json": "^2.2.375"
  "@react-spring/web": "^10.0.1"
  "@sentry/react": "^9"
  "@sentry/vite-plugin": "^3"
  "@svgr/core": "^8.1.0"
  "@svgr/plugin-jsx": "^8.1.0"
  "@tanstack/query-async-storage-persister": "^5.85.3"
  "@tanstack/react-query": "^5.85.3"
  "@tanstack/react-query-persist-client": "^5.85.3"
  "@tanstack/react-router": "^1.131.22"
  "@tanstack/router-plugin": "^1.131.22"
  "@tanstack/react-query-devtools": "^5.85.3"
  "@tanstack/react-router-devtools": "^1.131.22"
  "@types/node": "^22.15.32"
  "@types/react": "^19.1.10"
  "@types/react-dom": "^19.1.7"
  "@wagmi/core": "^2.17.2"
  cva: "npm:class-variance-authority@^0.7.1"
  globals: "^16.3.0"
  ox: "^0.8.4"
  prool: "^0.0.23"
  react: "^19.1.1"
  react-dom: "^19.1.1"
  sonner: "^2.0.7"
  tailwindcss: "^4.1.12"
  "@tailwindcss/vite": "^4.1.12"
  tw-animate-css: "^1.3.7"
  typescript: "^5.9.2"
  unplugin-icons: "^22.2.0"
  viem: "^2.33.2"
  vite: "^6.0.7"
  vitest: "^3.1.1"
  vite-plugin-mkcert: "^1.17.8"
  wagmi: "^2.15.4"
  zustand: "^5.0.3"
  "@vitejs/plugin-react": "^4.7.0"
  "@vitejs/plugin-react-swc": "^4.0.0"
