packages:
  - 'app'
  - 'examples/*'
  - 'extension'
  - 'playground'
  - 'src'

catalog:
  "@tanstack/react-query": "^5.59.20"
  "@types/react": "^18.3.3"
  "@types/react-dom": "^18.3.0"
  "@wagmi/core": "^2.16.3"
  globals: "^15.14.0"
  ox: "^0.6.4"
  react: "^19.0.0"
  react-dom: "^19.0.0"
  typescript: "^5.7.3"
  viem: "^2.22.21"
  wagmi: "^2.14.5"
