/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c1a4b0b83b880778151c664bab1f9d8b)
declare namespace Cloudflare {
  interface Env {
    NONCE_STORE: KVNamespace
  }
}
interface Env extends Cloudflare.Env {}
