/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1d34b249aada6580464f0661df2a5822)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env {
		NONCE_STORE: KVNamespace;
		JWT_SECRET: string;
		VITE_ENABLE_TUNNEL: string;
		CLOUDFLARE_TUNNEL_HOSTNAME: string;
		CLOUDFLARE_TUNNEL_SSL: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "JWT_SECRET" | "VITE_ENABLE_TUNNEL" | "CLOUDFLARE_TUNNEL_HOSTNAME" | "CLOUDFLARE_TUNNEL_SSL">> {}
}
