// This file was generated by theme-to-css.ts

import * as stylex from '@stylexjs/stylex'

export const theme = stylex.create({
  vars: {
    '--indicator': '#E3F1FB',
    '--indicator-content': '#0588F0',
    '--indicator-shape': 'circle',
    '--layer-background': '#EDEDED',
    '--layer-base': '#FCFCFC',
    '--layer-base-content': '#202020',
    '--layer-base-faint': '#D9D9D9',
    '--layer-base-muted': '#8D8D8D',
    '--layer-primary': '#3B9EFF',
    '--layer-primary-content': '#FFFFFF',
    '--layer-raised': '#FCFCFC',
    '--layer-raised-content': '#8D8D8D',
    '--layer-secondary': '#F0F0F0',
    '--layer-secondary-content': '#202020',
    '--radius-large': '14px',
    '--radius-medium': '8px',
    '--radius-small': '5px',
    '--separator-color': '#D9D9D9',
    '--separator-width': '1px',
    '--window-border-color': '#D9D9D9',
    '--window-border-width': '1px',
    '--window-shadow-color': '#00000012',
  },
})
