server:
  address: 0.0.0.0
  port: 9119
  metrics_port: 9120
  max_connections: 5000
chains:
  anvil:
    assets:
      ethereum:
        address: "0x0000000000000000000000000000000000000000"
        fee_token: true
        interop: false
    endpoint: http://anvil:8545
quote:
  constantRate: 1.0
  gas:
    intentBuffer: 100000
    txBuffer: 100000
  ttl: 30
  rateTtl: 300
transactions:
  num_signers: 16
  max_pending_transactions: 100
  max_transactions_per_signer: 16
  max_queued_per_eoa: 1
  balance_check_interval: 5
  nonce_check_interval: 60
  transaction_timeout: 60
  public_node_endpoints: {}
  priority_fee_percentile: 20.0
orchestrator:
legacy_orchestrators: []
legacy_delegation_proxies: []
delegation_proxy:
simulator:
funder:
escrow:
fee_recipient: '0x0000000000000000000000000000000000000000'
database_url: null
