/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b0e2fd7ae6527b21c3442eec5fccc59a)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker/index')
  }
  interface Env {
    NONCE_STORE: KVNamespace
    JWT_SECRET: string
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<Pick<Cloudflare.Env, 'JWT_SECRET'>> {}
}
