/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: dc969a5b9f5ced315ece20030feaff8d)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker/index')
  }
  interface Env {
    NONCE_STORE: KVNamespace
    JWT_SECRET: string
  }
}
interface Env extends Cloudflare.Env {}
