services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    entrypoint: ["anvil"]
    command: --odyssey --host 0.0.0.0 --port 8545
    labels:
      - dev.orbstack.domains=anvil.local
    ports:
      - "8545:8545"
    healthcheck:
      test: ["CMD", "cast", "block-number", "--rpc-url", "http://localhost:8545"]
      interval: 2s
      retries: 5

  config:
    depends_on:
      anvil:
        condition: service_healthy
    image: ghcr.io/foundry-rs/foundry:latest
    entrypoint: /bin/sh
    volumes:
      - ./config2.sh:/app/config2.sh
    command: -c "bash ./app/config2.sh"

  relay:
    image: ghcr.io/ithacaxyz/relay:latest
    labels:
      - dev.orbstack.domains=relay.local
    ports:
      - "9119:9119"
    volumes:
      - ./relay.yaml:/app/relay.yaml
    depends_on:
      config:
        condition: service_completed_successfully
    environment:
      RELAY_MNEMONIC: "test test test test test test test test test test test junk"
    command: --config-only
      
volumes:
  node_modules: