server:
  address: 127.0.0.1
  port: 9119
  metrics_port: 9120
  max_connections: 5000
chain:
  endpoints:
  - http://anvil:8545
  sequencer_endpoints: {}
  fee_tokens:
  - '0x0000000000000000000000000000000000000000'
  - 0xe1aa25618fa0c7a1cfdab5d6b456af611873b629
  fee_recipient: '0x0000000000000000000000000000000000000000'
quote:
  constantRate: null
  gas:
    intentBuffer: 100000
    txBuffer: 100000
  ttl: 30
  rateTtl: 300
onramp:
  banxa:
    apiUrl: https://api.banxa-sandbox.com/
    blockchain: base
    secrets:
      api_key: ''
transactions:
  num_signers: 16
  max_pending_transactions: 100
  max_transactions_per_signer: 16
  max_queued_per_eoa: 1
  balance_check_interval: 5
  nonce_check_interval: 60
  transaction_timeout: 60
  public_node_endpoints: {}
  priority_fee_percentile: 20.0
orchestrator: 0xa15bb66138824a1c7167f5e85b957d04dd34e468
legacy_orchestrators: []
legacy_delegations: []
delegation_proxy: 0x8ce361602b935680e8dec218b820ff5056beb7af
account_registry: 0x700b6a60ce7eaaea56f065753d8dcb9653dbad35
simulator: 0x196dbcbb54b8ec4958c959d8949ebfe87ac2aaaf
database_url: null
