[build]
builder = "DOCKERFILE"
buildCommand = "docker buildx build --tag porto-relay-mode --file Dockerfile . --no-cache --progress=plain"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
startCommand = "./server"
restartPolicyType = "ON_FAILURE"
