/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ThemeSwitchImport } from './routes/ThemeSwitch'
import { Route as ThemeImport } from './routes/Theme'
import { Route as ScreenImport } from './routes/Screen'
import { Route as FrameImport } from './routes/Frame'
import { Route as ButtonImport } from './routes/Button'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ThemeSwitchRoute = ThemeSwitchImport.update({
  id: '/ThemeSwitch',
  path: '/ThemeSwitch',
  getParentRoute: () => rootRoute,
} as any)

const ThemeRoute = ThemeImport.update({
  id: '/Theme',
  path: '/Theme',
  getParentRoute: () => rootRoute,
} as any)

const ScreenRoute = ScreenImport.update({
  id: '/Screen',
  path: '/Screen',
  getParentRoute: () => rootRoute,
} as any)

const FrameRoute = FrameImport.update({
  id: '/Frame',
  path: '/Frame',
  getParentRoute: () => rootRoute,
} as any)

const ButtonRoute = ButtonImport.update({
  id: '/Button',
  path: '/Button',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Button': {
      id: '/Button'
      path: '/Button'
      fullPath: '/Button'
      preLoaderRoute: typeof ButtonImport
      parentRoute: typeof rootRoute
    }
    '/Frame': {
      id: '/Frame'
      path: '/Frame'
      fullPath: '/Frame'
      preLoaderRoute: typeof FrameImport
      parentRoute: typeof rootRoute
    }
    '/Screen': {
      id: '/Screen'
      path: '/Screen'
      fullPath: '/Screen'
      preLoaderRoute: typeof ScreenImport
      parentRoute: typeof rootRoute
    }
    '/Theme': {
      id: '/Theme'
      path: '/Theme'
      fullPath: '/Theme'
      preLoaderRoute: typeof ThemeImport
      parentRoute: typeof rootRoute
    }
    '/ThemeSwitch': {
      id: '/ThemeSwitch'
      path: '/ThemeSwitch'
      fullPath: '/ThemeSwitch'
      preLoaderRoute: typeof ThemeSwitchImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Button': typeof ButtonRoute
  '/Frame': typeof FrameRoute
  '/Screen': typeof ScreenRoute
  '/Theme': typeof ThemeRoute
  '/ThemeSwitch': typeof ThemeSwitchRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Button': typeof ButtonRoute
  '/Frame': typeof FrameRoute
  '/Screen': typeof ScreenRoute
  '/Theme': typeof ThemeRoute
  '/ThemeSwitch': typeof ThemeSwitchRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Button': typeof ButtonRoute
  '/Frame': typeof FrameRoute
  '/Screen': typeof ScreenRoute
  '/Theme': typeof ThemeRoute
  '/ThemeSwitch': typeof ThemeSwitchRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Button' | '/Frame' | '/Screen' | '/Theme' | '/ThemeSwitch'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Button' | '/Frame' | '/Screen' | '/Theme' | '/ThemeSwitch'
  id:
    | '__root__'
    | '/'
    | '/Button'
    | '/Frame'
    | '/Screen'
    | '/Theme'
    | '/ThemeSwitch'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ButtonRoute: typeof ButtonRoute
  FrameRoute: typeof FrameRoute
  ScreenRoute: typeof ScreenRoute
  ThemeRoute: typeof ThemeRoute
  ThemeSwitchRoute: typeof ThemeSwitchRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ButtonRoute: ButtonRoute,
  FrameRoute: FrameRoute,
  ScreenRoute: ScreenRoute,
  ThemeRoute: ThemeRoute,
  ThemeSwitchRoute: ThemeSwitchRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Button",
        "/Frame",
        "/Screen",
        "/Theme",
        "/ThemeSwitch"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Button": {
      "filePath": "Button.tsx"
    },
    "/Frame": {
      "filePath": "Frame.tsx"
    },
    "/Screen": {
      "filePath": "Screen.tsx"
    },
    "/Theme": {
      "filePath": "Theme.tsx"
    },
    "/ThemeSwitch": {
      "filePath": "ThemeSwitch.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
