[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src",
    "solady/=lib/solady/src",
    "zklogin/=lib/zklogin/packages/contracts/contracts",
]
# via_ir = true # disabled due to Noir solidity verifier failing to compile
evm_version = "prague"
alphanet = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
