/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6f54276d4ab809c762a85c7c0f5b1630)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker/index')
  }
  interface Env {
    NONCE_STORE: KVNamespace
    PORT: string
    JWT_SECRET: string
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<Pick<Cloudflare.Env, 'PORT' | 'JWT_SECRET'>> {}
}
