#: schema https://esm.sh/wrangler/config-schema.json
# https://developers.cloudflare.com/workers/wrangler/configuration

# start of globally inheritable configuration
#
name = "offline-server-example"
main = "./src/main.ts"
minify = true
keep_vars = true
placement = { mode = "smart" }
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

#
# end of globally inheritable configuration

workers_dev = true
vars = { ENVIRONMENT = "development" }

[dev]
port = 6900

[[kv_namespaces]]
binding = "KEYS_01"
id = "e3099ba311184208a453ad289f2560f6"
preview_id = "1ce6744860ec4aaeabaa9b16a54d1e17"

[[d1_databases]]
binding = "DB"
database_name = "offline-demo-txs"
database_id = "80b220b8-9f1d-4179-8383-ddeeeac6fcf0"

[triggers]
crons = ["* * * * *"]

[env.production]
name = "offline-server-example"
workers_dev = true
vars = { ENVIRONMENT = "production" }

[[env.production.kv_namespaces]]
binding = "KEYS_01"
id = "e3099ba311184208a453ad289f2560f6"
preview_id = "1ce6744860ec4aaeabaa9b16a54d1e17"

[[env.production.d1_databases]]
binding = "DB"
database_name = "offline-demo-txs"
database_id = "bcc90687-1428-41ca-8825-20d84358e256"

[observability]
enabled = true
