// This file was generated by theme-to-css.ts

import * as stylex from '@stylexjs/stylex'

export const theme = stylex.create({
  vars: {
    '--indicator': '#0D2847',
    '--indicator-content': '#3B9EFF',
    '--indicator-shape': 'circle',
    '--layer-background': '#313131',
    '--layer-base': '#111111',
    '--layer-base-content': '#EEEEEE',
    '--layer-base-faint': '#646464',
    '--layer-base-muted': '#6E6E6E',
    '--layer-primary': '#3B9EFF',
    '--layer-primary-content': '#FFFFFF',
    '--layer-raised': '#111111',
    '--layer-raised-content': '#6E6E6E',
    '--layer-secondary': '#222222',
    '--layer-secondary-content': '#EEEEEE',
    '--radius-large': '0px',
    '--radius-medium': '0px',
    '--radius-small': '0px',
    '--separator-color': '#222222',
    '--separator-width': '1px',
    '--window-border-color': '#222222',
    '--window-border-width': '1px',
    '--window-shadow-color': '#00000033',
  },
})
