name: Auto Assign PR to Author

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  auto-assign:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
    steps:
      - name: Check Membership
        run: |
          gh api orgs/${{ env.REPO }}/members/${{ env.PR_AUTHOR }} --silent 2> /dev/null \
            && echo "IS_ORG_MEMBER=true" >> $GITHUB_ENV || echo "IS_ORG_MEMBER=false" >> $GITHUB_ENV

      - name: Auto assign PR to author
        if: ${{ env.IS_ORG_MEMBER == 'true' }}
        env:
          IS_ORG_MEMBER: ${{ env.IS_ORG_MEMBER }}
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request

            if (pr.assignees.length > 0 || pr.user.type.toLowerCase() === 'bot') return

            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              assignees: [${{ env.PR_AUTHOR }}]
            })
              .then(() => console.info(`Successfully assigned PR #${pr.number} to ${{ env.PR_AUTHOR }}`))
              .catch((error) => console.error(error))
