name: Auto Assign PR to Author

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-assign:
    permissions:
      issues: write
      pull-requests: write
    uses: ithacaxyz/ci/.github/workflows/auto-assign-pr.yml@d326eafa6b9790b974ce1396bd4634c3cf0953b3 # main
