name: Deploy Workers

on:
  push:
    branches: [main]
    paths:
      - 'apps/service/**'
      - 'apps/~internal/**'
      - 'src/trusted-hosts.ts'
      - '.github/workflows/deploy-workers.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  deploy:
    name: 'Deploy'
    timeout-minutes: 3
    runs-on: ['ubuntu-latest']
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: 🔸 Cloudflare Workers - Deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          APP_VERSION: ${{ github.sha }}
        working-directory: apps/service
        run: |
          pnpm dlx wrangler@latest deploy \
            --config='wrangler.json' \
            --keep-vars \
            --var 'APP_VERSION:${{ github.sha }}'
