name: Deploy Workers

on:
  push:
    branches: [main]
    paths:
      - 'apps/service/**'
      - 'apps/~internal/**'
      - 'src/trusted-hosts.ts'
      - '.github/workflows/deploy-workers.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  deploy:
    name: 'Deploy'
    timeout-minutes: 3
    runs-on: ['ubuntu-latest']
    steps:
      - name: Clone repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          submodules: 'recursive'

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Set App Version
        run: echo "APP_VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: 🔸 Cloudflare Workers - Deploy
        env:
          APP_VERSION: ${{ env.APP_VERSION }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        working-directory: apps/service
        run: |
          pnpm dlx wrangler@latest deploy \
            --config='wrangler.json' \
            --keep-vars \
            --var 'ENVIRONMENT:production' \
            --var 'APP_VERSION:${{ env.APP_VERSION }}'
