name: Deploy Faucet

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      DRIP_PRIVATE_KEY:
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  deploy:
    name: 'Deploy'
    timeout-minutes: 3
    runs-on: ['ubuntu-latest']
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Update DRIP_PRIVATE_KEY if provided
        if: inputs.DRIP_PRIVATE_KEY != ''
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          echo ${{ inputs.DRIP_PRIVATE_KEY }} | pnpm dlx wrangler@latest secret put DRIP_PRIVATE_KEY

      - name: 🔸 Cloudflare Workers - Deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: pnpm --filter faucet run deploy
