name: Main
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  extension:
    name: Extension
    needs: verify
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Zip
        run: |
          pnpm --filter extension zip
          pnpm --filter extension zip:firefox

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: apps/extension/.output

  changesets:
    name: Changesets
    needs: verify
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set up pnpm
        uses: wevm/actions/.github/actions/pnpm@main

      - name: PR or publish
        uses: changesets/action@06245a4e0a36c064a573d4150030f5ec548e4fcc
        with:
          title: 'chore: version packages'
          commit: 'chore: version packages'
          createGithubReleases: ${{ github.ref == 'refs/heads/main' }}
          publish: pnpm changeset:publish
          version: pnpm changeset:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
