name: Promote Apps to Production
on:
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  promote:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          app: [dialog, docs, manage, playground, wagmi]
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Promote App (${{ matrix.app }}) to Production
        continue-on-error: true
        run: vercel promote ${{ matrix.app }}porto-ithacaxyz.vercel.app --token=${{ secrets.VERCEL_TOKEN }} --scope=ithacaxyz