name: Verify
on:
  workflow_call:
  workflow_dispatch:
  repository_dispatch:
    types: ['relay-release', 'relay-deployment']

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Check code
        run: pnpm check

      - name: Check types
        run: pnpm check:types

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        run: pnpm build

      - name: Check build
        run: pnpm check:build

      - name: Check for unused files, dependencies, and exports
        run: pnpm check:knip

      - name: Check size
        run: pnpm check:size

  test:
    name: Tests (${{ matrix.local == 'true' && 'Local' || 'Deployment' }}, ${{ matrix.browser == 'true' && 'Browser' || 'Node' }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        # Only run deployment tests on main branch or when triggered by a repository dispatch.
        local: ${{ fromJSON((github.ref == 'refs/heads/main' || github.event_name == 'repository_dispatch') && '["true", "false"]' || '["true"]') }}
        browser: ['true', 'false']
    env: 
      CI: true
      VITE_LOCAL: ${{ matrix.local }}
      VITE_ANVIL_FORK_URL: ${{ secrets.VITE_ANVIL_FORK_URL }}
      VITE_FAUCET_PRIVATE_KEY: ${{ secrets.VITE_FAUCET_PRIVATE_KEY }}
      VITE_FAUCET_PRIVATE_KEY_RELEASE: ${{ secrets.VITE_FAUCET_PRIVATE_KEY_RELEASE }}
      VITE_FAUCET_PRIVATE_KEY_DEPLOYMENT: ${{ secrets.VITE_FAUCET_PRIVATE_KEY_DEPLOYMENT }}
      VITE_DISPATCH_TYPE: ${{ github.event_name == 'repository_dispatch' && github.event.action || '' }}
      VITE_GECKO_API: ${{ secrets.VITE_GECKO_API }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Set up Docker
        if: matrix.local == 'true'
        uses: docker/setup-docker-action@v4

      - name: Login to GitHub Container Registry
        if: matrix.local == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: jxom
          password: ${{ secrets.RELAY_GH_TOKEN }}

      - name: Install Playwright
        if: matrix.browser == 'true'
        run: pnpx playwright install --with-deps

      - name: Test
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: pnpm ${{ matrix.browser == 'true' && 'test:browser' || 'test' }} ${{ matrix.local == 'true' && '--bail=1 --retry=3' || '' }}