name: Verify
on:
  workflow_call:
  workflow_dispatch:
  repository_dispatch:
    types: ['relay-release', 'relay-deployment']

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Check code
        run: pnpm check

      - name: Check types
        run: pnpm check:types

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        run: pnpm build

      - name: Check build
        run: pnpm check:build

      - name: Check for unused files, dependencies, and exports
        run: pnpm check:knip

      - name: Check size
        run: pnpm check:size

  test:
    name: Tests (${{ matrix.local == 'true' && 'Local' || 'Deployment' }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        local: ['true', 'false']

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Set up Docker
        if: matrix.local == 'true'
        uses: docker/setup-docker-action@v4

      - name: Login to GitHub Container Registry
        if: matrix.local == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: jxom
          password: ${{ secrets.RELAY_GH_TOKEN }}

      - name: Pull Relay
        if: matrix.local == 'true'
        shell: bash
        run: docker pull ghcr.io/ithacaxyz/relay:latest

      - name: Test
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: pnpm test:ci ${{ matrix.local == 'true' && '--bail=1 --retry=3' || '' }}
        env: 
          VITE_LOCAL: ${{ matrix.local }}
          VITE_ANVIL_FORK_URL: ${{ secrets.VITE_ANVIL_FORK_URL }}
          VITE_FAUCET_PRIVATE_KEY: ${{ secrets.VITE_FAUCET_PRIVATE_KEY }}
          VITE_GECKO_API: ${{ secrets.VITE_GECKO_API }}
